### ISSUE TITLE
Auto Scaling Group assumes successful AZ spread

### ISSUE THREAD

**Issue by mifisignal** [LeanerCloud/ec2-repair-crowdstrike#1]
The current design of the ASG in the Terraform script assumes that the instances launched will be spread among all the AZs in the list. EC2 Auto Scaling doesn't guarantee that. If you want to ensure a 1:1 correlation between instances and AZs, you'll need to create an AZ per ASG with a single subnet binding for each.

**Comment by cristim** [comment]
I'm surprised to see this, as far as I know ASGs enforce the even number through the AZ rebalancing process when the number of instances is unbalanced.

**Comment by mifisignal** [comment]
AZ rebalancing is best-effort, but not guaranteed. For example, if there is a shortage of a particular instance type in an AZ, EC2 Auto Scaling will launch the instance in a different AZ if possible. This would result in an imbalance. 

Unless you've disabled the rebalancing process, Auto Scaling will try to rebalance from time to time, but again, not a guarantee.

**Comment by cristim** [comment]
@otterley thanks for the clarifications, I ditched the ASGs and now just provisioned individual instances.
